import type { Metadata } from "next";
import {Inter} from "next/font/google";
import { ThemeProvider } from "next-themes";
import { AuthProvider } from "./AuthProvider";
import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "@/components/ui/sonner";



const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${inter.className} dark:animated-dotted-background`}
        >
          <ThemeProvider attribute="class">
            <ConvexClientProvider>
            {children}
            <Toaster />

            </ConvexClientProvider>
            
            </ThemeProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
